# Generated by Django 4.1.7 on 2023-05-16 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student_qr",
            name="student_qr",
            field=models.FileField(upload_to="uploads/"),
        ),
    ]
